name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends
  - abseil-cpp
  - aiobotocore
  - aiohttp
  - aioitertools
  - aiosignal
  - alabaster
  - altair
  - anaconda-anon-usage
  - anaconda-catalogs
  - anaconda-client
  - anaconda-cloud-auth
  - anaconda-navigator
  - anaconda-project
  - anyio
  - aom
  - appdirs
  - archspec
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - arrow-cpp
  - astroid
  - astropy
  - asttokens
  - async-lru
  - atomicwrites
  - attrs
  - automat
  - autopep8
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - babel
  - backports
  - backports.functools_lru_cache
  - backports.tempfile
  - backports.weakref
  - bcrypt
  - beautifulsoup4
  - binaryornot
  - black
  - blas
  - bleach
  - blinker
  - blosc
  - bokeh
  - boltons
  - boost-cpp
  - botocore
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - cfitsio
  - chardet
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - clyent
  - colorama
  - colorcet
  - comm
  - conda
  - conda-build
  - conda-content-trust
  - conda-index
  - conda-libmamba-solver
  - conda-pack
  - conda-package-handling
  - conda-package-streaming
  - conda-repo-cli
  - conda-token
  - conda-verify
  - constantly
  - contourpy
  - cookiecutter
  - cryptography
  - cssselect
  - curl
  - cycler
  - cytoolz
  - dask
  - dask-core
  - datashader
  - dav1d
  - debugpy
  - decorator
  - defusedxml
  - diff-match-patch
  - dill
  - distributed
  - distro
  - docstring-to-markdown
  - docutils
  - entrypoints
  - et_xmlfile
  - executing
  - filelock
  - flake8
  - flask
  - fmt
  - fonttools
  - freetype
  - frozendict
  - frozenlist
  - fsspec
  - future
  - gensim
  - gflags
  - giflib
  - gitdb
  - gitpython
  - glog
  - gmpy2
  - greenlet
  - grpc-cpp
  - h5py
  - hdf5
  - heapdict
  - holoviews
  - hvplot
  - hyperlink
  - icu
  - idna
  - imagecodecs
  - imageio
  - imagesize
  - imbalanced-learn
  - importlib-metadata
  - importlib_metadata
  - incremental
  - inflection
  - iniconfig
  - intake
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itemadapter
  - itemloaders
  - itsdangerous
  - jaraco.classes
  - jedi
  - jellyfish
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - jq
  - json5
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab-variableinspector
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - lazy_loader
  - lcms2
  - lerc
  - libaec
  - libarchive
  - libavif
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcurl
  - libdeflate
  - libevent
  - libffi
  - libiconv
  - liblief
  - libmamba
  - libmambapy
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libsolv
  - libspatialindex
  - libssh2
  - libthrift
  - libtiff
  - libwebp-base
  - libxml2
  - libxslt
  - libzopfli
  - linkify-it-py
  - llvmlite
  - locket
  - lxml
  - lz4
  - lz4-c
  - lzo
  - markdown
  - markdown-it-py
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - mdit-py-plugins
  - mdurl
  - menuinst
  - mistune
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multidict
  - multipledispatch
  - munkres
  - mypy
  - mypy_extensions
  - navigator-updater
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - nltk
  - notebook
  - notebook-shim
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - openjpeg
  - openpyxl
  - openssl
  - orc
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - panel
  - param
  - paramiko
  - parsel
  - parso
  - partd
  - pathlib
  - pathspec
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkce
  - pkginfo
  - platformdirs
  - plotly
  - pluggy
  - ply
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - protego
  - protobuf
  - psutil
  - ptyprocess
  - pure_eval
  - py-cpuinfo
  - py-lief
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pybind11-abi
  - pycodestyle
  - pycosat
  - pycparser
  - pyct
  - pycurl
  - pydantic
  - pydeck
  - pydispatcher
  - pydocstyle
  - pyerfa
  - pyflakes
  - pygments
  - pyjwt
  - pylint
  - pylint-venv
  - pyls-spyder
  - pymysql
  - pynacl
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pyqtwebengine
  - pysocks
  - pytables
  - pytest
  - python
  - python-dateutil
  - python-dotenv
  - python-fastjsonschema
  - python-json-logger
  - python-libarchive-c
  - python-lmdb
  - python-lsp-black
  - python-lsp-jsonrpc
  - python-lsp-server
  - python-slugify
  - python-snappy
  - python-tzdata
  - pytoolconfig
  - pytz
  - pyviz_comms
  - pywavelets
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qstylizer
  - qt-main
  - qt-webengine
  - qtawesome
  - qtconsole
  - qtpy
  - queuelib
  - re2
  - referencing
  - regex
  - reproc
  - reproc-cpp
  - requests
  - requests-file
  - requests-toolbelt
  - rfc3339-validator
  - rfc3986-validator
  - rich
  - rope
  - rpds-py
  - rtree
  - ruamel.yaml
  - ruamel_yaml
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - semver
  - send2trash
  - service_identity
  - setuptools
  - sip
  - six
  - smart_open
  - smmap
  - snappy
  - sniffio
  - snowballstemmer
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - stack_data
  - statsmodels
  - streamlit
  - sympy
  - tabulate
  - tbb
  - tblib
  - tenacity
  - terminado
  - text-unidecode
  - textdistance
  - threadpoolctl
  - three-merge
  - tifffile
  - tinycss2
  - tk
  - tldextract
  - toml
  - tomlkit
  - toolz
  - tornado
  - tqdm
  - traitlets
  - truststore
  - twisted
  - typing-extensions
  - typing_extensions
  - tzdata
  - tzlocal
  - uc-micro-py
  - ujson
  - unidecode
  - urllib3
  - utf8proc
  - validators
  - w3lib
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - whatthepatch
  - wheel
  - widgetsnbextension
  - wrapt
  - xarray
  - xlwings
  - xyzservices
  - xz
  - yaml
  - yaml-cpp
  - yapf
  - yarl
  - zeromq
  - zfp
  - zict
  - zipp
  - zlib
  - zlib-ng
  - zope
  - zope.interface
  - zstandard
  - zstd
